# ─────────────────────────────────────────────────────────
# 프로젝트 이름 설정
# 지정하지 않으면 디렉토리 이름(mbti)으로 자동 사용
name: mbti

# ─────────────────────────────────────────────────────────
# 서비스 정의 (반드시 필요)
services:
  # ┌──────────────────────────────────────────────────────
  # │ 앱 애플리케이션 컨테이너
  app:
    # 사용할 이미지 이름(태그)
    image: toby/mbti:mysql

    # 이미지가 없을 때 빌드 설정
    build:
      # ─ 빌드 아규먼트
      args:
        - NODE_VERSION=20.15.1
      # ─ Dockerfile 경로
      dockerfile: ./Dockerfile
      # ─ 항상 최신 베이스 이미지를 pull
      pull: true
      # ─ 빌드 컨텍스트 디렉토리
      context: .

    # 컨테이너 이름을 고정
    container_name: app

    # 환경변수 설정
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db_mbti
      - DB_USERNAME=user_mbti
      - DB_PASSWORD=pw_mbti

    # 연결할 네트워크 목록
    networks:
      - mbti-net

    # 호스트와 컨테이너 간 포트 매핑 (호스트:컨테이너)
    ports:
      - 4000:3000

  # ┌──────────────────────────────────────────────────────
  # │ 데이터베이스 컨테이너
  db:
    # MySQL 공식 이미지 사용
    image: mysql:8.3.0

    # 컨테이너 이름을 고정
    container_name: db

    # MySQL 초기 설정용 환경변수
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=db_mbti
      - MYSQL_USER=user_mbti
      - MYSQL_PASSWORD=pw_mbti

    # 연결할 네트워크
    networks:
      - mbti-net

    # 데이터 영속성을 위한 볼륨 마운트 (호스트 볼륨:컨테이너 디렉토리)
    volumes:
      - mbti-vol:/var/lib/mysql

# ─────────────────────────────────────────────────────────
# 사용자 정의 네트워크 선언
networks:
  mbti-net:
    # 실제 생성될 네트워크 이름 지정
    name: mbti-net

# ─────────────────────────────────────────────────────────
# 볼륨 선언 (데이터 영속성 확보)
volumes:
  mbti-vol:
    # 실제 생성될 볼륨 이름 지정
    name: mbti-vol
